# Site wide configuration

title:            lmnt.co tech blog
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Jeff Barrows
  avatar: http://www.gravatar.com/avatar/27ff50338055cd0ec8b897d7314c2eb4.png
  bio: "Innovation through applied technology."
  email:
  disqus-shortname: dj_splice
  twitter: barrows_jeff
  facebook: #username
  google:
    plus: LmntCode
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: djsplice
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: jbarrows
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
